project:
  type: website
  output-dir: docs
  resources: ["CNAME"]
  
lang: tr
  
execute:
    freeze: auto
    
comments:
  giscus:
    repo: "kaansevim/rapor"
    

website:
  image: "images/png4.png"
  favicon: "images/png4.png"
  
  reader-mode: true
  
  
  repo-url:    https://github.com/kaansevim/rapor
  repo-branch: main
  repo-actions: [edit, issue]
  
  navbar:
    title: "<span class='brand-r2'>R<sup>2</sup></span>"
    background: primary
    right:
      - text: "Ana Sayfa"
        href: index.qmd
      - text: "Analizler"
        file: analizler/index.qmd
      - text: "Veri Görsel"
        file: verigorsel/index.qmd
      - text: "Blog"
        file: blog/index.qmd
      - text: "Araştırma Yöntemleri"
        file: research/index.qmd
      - text: "Katkı"
        file: katkı.qmd
      - text: "İletişim"
        file: iletisim.qmd
      - icon: github
        href: https://github.com/kaansevim/rapor
      - icon: twitter
        href: https://x.com/kaanswm
      - icon: linkedin
        href: https://www.linkedin.com/in/kaan-sevim-43043875/
        
  sidebar: 
    - title: "Araştırma Yöntemleri"
      style: docked
      search: false
      background: dark
      contents:
      - section: "Genel Giriş"
        contents:
          - text: "R Programlama İle Araştırma Analizleri"
            file: research/index.qmd
          - text: "R ve RStudio Kurulumu"
            file: research/rkurulumm.qmd
      - section: "I. Bölüm"
        contents:
          - text: "1: Betimsel ve Çıkarımsal İstatistikler"
            file: research/01-research.qmd
          - text: "2: Araştırma Türleri ve Tasarımları"
            file: research/02-research.qmd
          - text: "3: Betimleyici Araştırma Yöntemleri"
            file: research/03-research.qmd
          - text: "4: Deneysel Araştırma Yöntemleri"
            file: research/04-research.qmd
          - text: "5: Ölçme Araçları ve Anket Tasarımı"
            file: research/05-research.qmd
          - text: "6: Ölçek Geliştirme ve Geçerlilik"
            file: research/06-research.qmd
          - text: "7: Örneklem Seçimi ve Örneklem Büyüklüğü"
            file: research/07-research.qmd
      - section: "II. Bölüm"
        contents:
          - text: "8: Veri Toplama Teknikleri"
            file: research/08-research.qmd
          - text: "9: Nitel Araştırma Yöntemleri"
            file: research/09-research.qmd
          - text: "10: İçerik Analizi ve Tematik Kodlama"
            file: research/10-research.qmd
          - text: "11: Durum Çalışması ve Etnografi"
            file: research/11-research.qmd
          - text: "12: Değişkenler Arası İlişkilerin Analizi"
            file: research/12-research.qmd
          - text: "13: SPSS ve R ile Veri Analizi Temelleri"
            file: research/13-research.qmd
          - text: "14: Bulguların Yorumlanması ve Raporlama"
            file: research/14-research.qmd
          - text: "15: Etik Kurallar ve Araştırma Yazımı"
            file: research/15-research.qmd
      
  page-footer:
    background: light
    left: |
      <img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" 
         alt="" 
         style="max-width:1em;max-height:1em;margin-left:.2em;">
       <img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" 
         alt="" 
         style="max-width:1em;max-height:1em;margin-left:.2em;">
      <a href="https://kaansevim.github.io/rapor/">R²apor;</a> 
      <a href="https://creativecommons.org"></a>
      <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> ile lisanlanmşıtır.
    center: 
      - text: Hakkımızda
        href: index.qmd
      - text: Lisans
        href: https://github.com/kaansevim/rapor/tree/master?tab=MIT-1-ov-file#readme
      - text: İletişim
        href: iletisim.qmd
    right: 
      - icon: github
        href: https://github.com/kaansevim/rapor
    

  site-url: www.rrapor.com


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
  
reference-location: section
reference-section-title: "Kaynaklar"
