project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "Ana Sayfa"
        href: index.qmd
      - text: "Analizler"
        href: analizler.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Hakkımızda"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/kaansevim/rapor
      - icon: twitter
        href: https://x.com/kaanswm

format:
  html:
    theme:
      light: [cosmo, styles.scss]
    css: styles.css

editor: visual
